### ISSUE TITLE
The procedure entry point

### ISSUE THREAD

**Issue by Cezar512** [secrary/makin#2]
After building solution when I try to run makin.exe just like you did I'm getting error:
```
The procedure entry point WaitForDebugEventEx could not be located in the dynamic link libary KERNEL32.dll
```
Im using Windows 7 64x

**Comment by secrary** [comment]
According to `MSDN`: Minimum supported client - Windows 10
![image](https://user-images.githubusercontent.com/16405698/38599726-30005aca-3d51-11e8-853b-9b34463447cc.png)

https://msdn.microsoft.com/en-us/library/windows/desktop/mt171594(v=vs.85).aspx
