### ISSUE TITLE
[EXCEPTION] EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by ghost** [secrary/makin#3]
Apon using the program, it returns this error twice -

[EXCEPTION] EXCEPTION_ACCESS_VIOLATION

Any help?

 I'm very new to reverse engineering, thanks! :)

**Comment by secrary** [comment]
Can you share the sample?

**Comment by ghost** [comment]
Here's the program I'm trying to debug - https://mega.nz/#!MTQnHT5S!VywIRyKWxFAkMAUmwrFFGjfZQvFgOU62yQ6pxSJVjo8

Thanks for the quick reply

**Comment by secrary** [comment]
The sample is protected by [Obsidium](https://www.obsidium.de/) software protection system, 
maybe it checks the existence of a debugger via reading PEB.BeingDebugged field or something similar and behaves differently, at this moment `makin` cannot detect such direct memory accesses, 
or maybe that's an intended exception to detect if a debugger is there or not

**Comment by ghost** [comment]
Okay thanks! Just for some help, how did you figure out it was protected by Obsidium?

**Comment by secrary** [comment]
Using this tool: http://exeinfo.atwebpages.com/

**Comment by ghost** [comment]
Thanks for all the help 👍 I've just started learning reverse engineering and it's all really confusing right now.

**Comment by secrary** [comment]
I recommend this book: https://beginners.re/RE4B-EN.pdf for RE
