### ISSUE TITLE
Sir, I have a question.

### ISSUE THREAD

**Issue by ghost** [secrary/makin#4]
Hello, sir! I have a problem.
My boss want me to write a function, to check up some ntdll's thing is/not hooked, like "NtQueryInformationProcess".
I have no idea how to do this... Can you give me a idea or code? Thank you very much!

**Comment by secrary** [comment]
I think this can answer your question:  https://security.stackexchange.com/questions/17904/what-are-the-methods-to-find-hooked-functions-and-apis
